language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
install:
  - pip install -q Django==$DJANGO
  - pip install flake8
  - pip install coveralls
  - pip install -q -e .
before_script:
  - "flake8 tabbed_admin"
script:
  - coverage run --source tabbed_admin_u tabbed_admin_u/tests/runtests.py
after_success: coveralls
